name: 'dertour_dw'
version: '1.0.0'
config-version: 2

profile: 'dertour'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dertour_dw:
    staging:
      +schema: staging
      +materialized: view
      +tags: ['staging']
    intermediate:
      +schema: intermediate
      +materialized: view
      +tags: ['intermediate']
    marts:
      +schema: marts
      +materialized: table
      +tags: ['marts']

vars:
  start_date: '2022-01-01'
  end_date: '2025-12-31'
